project_id = "knldnlwpsrhcgvlbjsyx"

[functions.analyze-vision]
verify_jwt = false

[functions.analyze-website]
verify_jwt = false

[functions.auto-optimize-scheduler]
verify_jwt = false

[functions.compliance-scanner]
verify_jwt = false

[functions.ab-test-manager]
verify_jwt = false
